# Generated by Django 4.1.4 on 2022-12-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='conf_password',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
