# Generated by Django 4.1.4 on 2022-12-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_info_conf_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='conf_password',
        ),
    ]
